export const leagueID = "1253040502786228224";
export const leagueName = "Irving Champions League";
export const dues = 100;
export const dynasty = false;
export const enableBlog = true;

export const homepageText = `
  <p>Introducing the Irving Champions League.</p>
  <p>
    Born from the ashes of two legendary leagues—The Irving League and DTSP—the
    <strong>Irving Champions League</strong> unites the fiercest competitors into
    one ultimate arena. This is no ordinary fantasy football league; it’s a clash
    of titans, where the best of the best now battle for a single crown.
  </p>
  <p><strong>Welcome to the next chapter.</strong></p>
`;

export const managers = [
  { //array 0
    managerID: "1253772062900621312",
    name: "Dave Oliverio",
    teamName: "Lehigh Crucible",
    location: "PA",
    bio: "The Lehigh Crucible isn’t just a fantasy football team—it’s a blast furnace of grit, forged in the heart of Pennsylvania where only the toughest survive. The Crucible attack their opponents loud and fast like a basement punk rock show! This team is built on a setlist fueled by sing-a-long choruses and lines of secret code. Turn it up, burn it down, and win loud!",
    photo: "/managers/crucible.png",
    fantasyStart: 2004,
    favoriteTeam: "nyg",
    mode: "Rebuild",
    rival: { name: "Kevin", link: 5, image: "/managers/nakatomi.png" },
    yearsOfService: "Twenty",
    persona: "The Wolf",
    philosophy: "Never leave without setting something on fire.",
    championship: { league: "Irving", years: "2004" },
    preferredContact: "Text"
  },
  { // array 1
    managerID: "76521957268799488",
    name: "Jeff Cohn",
    teamName: "Ultimate City Warriors",
    location: "FL",
    bio: "The Ultimate City Warriors charge into every fantasy matchup with neon fury and rope-shaking madness. Fueled by chaos, face paint, and pure gridiron intensity, the Warriors turn every game into a pay-per-view spectacle. Hesitation is defeat—Warriors run wild, Warriors run right over you. Feel the Power!",
    photo: "/managers/warriors.png",
    fantasyStart: 2004,
    favoriteTeam: "mia",
    mode: "Rebuild",
    rival: { name: "Jamie", link: 2, image: "/managers/lightsabres.png" },
    yearsOfService: "Twenty",
    persona: "The Littlefinger",
    philosophy: "Feel the power!",
    championship: { league: "Irving", years: "2009, 2011, 2019, 2021" },
    preferredContact: "Text"
  },
  { // array 2
    managerID: "1253515645044133888",
    name: "Jamie Cohn",
    teamName: "Dagobah Lightsabres",
    location: "FL",
    bio: "The Dagobah Lightsabres are forged in the swamp—trained in the ways of the Force. Its General Manager studied under a wise, small, green fantasy master whose advice was simple but powerful. Do or do not. There is no try. Each year's draft is a rite of passage to Dagobah! When the season gets dark and the standings get muddy, this team is battle-tested. Dagobah does not fear the dark side because in the end, champions are not made in comfort. Champions are forged in the swamp!",
    photo: "/managers/lightsabres.png",
    fantasyStart: 2004,
    favoriteTeam: "pit",
    mode: "Rebuild",
    rival: { name: "Jeff", link: 1, image: "/managers/warriors.png" },
    yearsOfService: "Twenty",
    persona: "The Kornacki",
    philosophy: " True champions are forged in the swamp.",
    championship: { league: "Irving", years: "2008, 2018" },
    preferredContact: "Text"
  },
  { // array 3
    managerID: "1005329348477419520",
    name: "Kenny Case",
    teamName: "Rebel Radio Lone Rangers",
    location: "FL",
    bio: "The Lone Rangers hijack the fantasy football frequency like a rogue pirate radio station—blasting chaos, touchdowns, and trash talk across the league’s airwaves. Led by an attorney who cross-examines every stat and prosecutes every matchup, Rebel Radio don’t just beat you, they broadcast your defeat in stereo. One team, one mission, and no license to turn the volume down.",
    photo: "/managers/loneRangers.png",
    fantasyStart: 2011,
    favoriteTeam: "ne",
    mode: "Rebuild",
    rival: { name: "James Barmore", link: 9, image: "/managers/homers.png" },
    yearsOfService: "Ten",
    persona: "The Flacco",
    philosophy: "This league is a frequency to be hijacked!",
    championship: { league: "Irving", years: "2013, 2017" },
    preferredContact: "Text"
  },
  { // array 4
    managerID: "1254577682394386432",
    name: "Clifton McVay",
    teamName: "Salem Hipsterjacks",
    location: "FL",
    bio: "The Salem Hipsterjacks blend Oregon trail grit with an engineer’s precision—drafting rosters as carefully as they’d handcraft a cedar canoe. Outdoorsy, calculated, and just a little ahead of the curve, Salem spots breakout players before they’re cool and dismantle opponents with quiet, flannel-clad efficiency. In this league, the Hipsterjacks measure twice, cut deep, and win big.",
    photo: "/managers/hipsterJacks.png",
    fantasyStart: 2015,
    favoriteTeam: "gb",
    mode: "Rebuild",
    rival: { name: "Brian James", link: 10, image: "/managers/kodachromes.png" },
    yearsOfService: "Ten",
    persona: "The Wolf",
    philosophy: "Measure twice, cut deep, and win big.",
    championship: { league: "DTSP", years: "2023" },
    preferredContact: "Text"
  },
  { // array 5
    managerID: "1254577895943192576",
    name: "Kevin Flanagan",
    teamName: "Nakatomi Plaza CC",
    location: "CT",
    bio: "The Nakatomi Custodial Crew cleans up the league Die Hard–style—crawling through the ducts, surviving the explosions, and mopping the floor with every opponent. Led by a GM who always has one last trick taped to his back, the Crew strikes when it matters most, pulling off clutch wins worthy of a Kerry Kittles highlight reel. Barefoot, relentless, and armed with a trophy case that never needs dusting.",
    photo: "/managers/nakatomi.png",
    fantasyStart: 2005,
    favoriteTeam: "ne",
    mode: "Rebuild",
    rival: { name: "Dave", link: 0, image: "/managers/crucible.png" },
    yearsOfService: "Twenty",
    persona: "The Littlefinger",
    philosophy: "Yippee-ki-yay, motherfuckers!",
    championship: { league: "Irving", years: "2016, 2023, 2024" },
    preferredContact: "Text"
  },
  { // array 6
    managerID: "1254578120531390464",
    name: "Drew Goodwin",
    teamName: "Amherst Union",
    location: "FL",
    bio: "The Amherst Union plays fantasy football the way their small town works—together, with grit, pride, and a little Cleveland-born stubbornness. Every roster spot has a job, every win is a crew victory, and every opponent is just another strike to shut down. United we stand, and when the season ends, we hoist the trophy like it’s a contract well-earned.",
    photo: "/managers/union.png",
    fantasyStart: 2022,
    favoriteTeam: "cle",
    mode: "Rebuild",
    rival: { name: "Romano DeSimone", link: 8, image: "/managers/vincitori.png" },
    yearsOfService: null,
    persona: "The Littlefinger",
    philosophy: "Outwork the opposition and STAND UNITED!",
    championship: { league: "DTSP", years: "2024" },
    preferredContact: "Text"
  },
  { // array 7
    managerID: "1254584226238447616",
    name: "Jason Gray",
    teamName: "Milford Jayhawks",
    location: "CT",
    bio: "The Milford Jayhawks see the whole field like it’s “Scenario,” spotting big plays before they even drop. Rooted in Milford Connecticut spirit, the Jayhawks draft smart, play smooth, and always “kick it” when it counts—“you on point, Jay?” “All the time.” In this league, perspective is everything—and Milford has the view to win it all.",
    photo: "/managers/jayhawks.png",
    fantasyStart: 2004,
    favoriteTeam: "mia",
    mode: "Rebuild",
    rival: { name: "Adam Lopiano", link: 12, image: "/managers/mounties.png" },
    yearsOfService: "Twenty",
    persona: "The Flacco",
    philosophy: "On point, all the time",
    championship: { league: "Irving", years: "2005" },
    preferredContact: "Text"
  },
  { // array 8
    managerID: "792114259365597184",
    name: "Romano DeSimone",
    teamName: "Jacksonville Vincitori",
    location: "FL",
    bio: "In Duval County, football isn’t just a pastime—it’s a calling! Vincitori is “winners” in Italian, in case your nonna didn’t teach you that! Every season, the Lords of Jacksonville are on an epic journey to build one team to rule them all! Dare to cross them and you will get a smack like every other paisano who ever dared to leave a cannoli on their plate!",
    photo: "/managers/vincitori.png",
    fantasyStart: 2015,
    favoriteTeam: "ne",
    mode: "Rebuild",
    rival: { name: "Brian Marx", link: 11, image: "/managers/tribe.png" },
    yearsOfService: "Ten",
    persona: "The Flacco",
    philosophy: "One team to rule them all, Duval forever!",
    championship: { league: "DTSP", years: "2016, 2017, 2018" },
    preferredContact: "Text"
  },
  { // array 9
    managerID: "1256695342544453632",
    name: "James Barmore",
    teamName: "Dunedin Homers",
    location: "FL",
    bio: "The Dunedin Homers aren’t just a fantasy football team, they are a carefully crafted small-batch Championship brew with unapologetic homer energy. Fiercely loyal, they are Homers in every sense of the word-- with stubborn pride and a little bit of pirate mischief. In Dunedin, they don’t just cheer for their team… they raise a pint to it.",
    photo: "/managers/homers.png",
    fantasyStart: 2007,
    favoriteTeam: "tb",
    mode: "Rebuild",
    rival: { name: "Jamie Cohn", link: 2, image: "/managers/lightsabres.png" },
    yearsOfService: "Ten",
    persona: "The Kornacki",
    philosophy: "Brewed strong, loyal to the last drop, fire the cannons!",
    championship: { league: "Irving", years: "2020" },
    preferredContact: "Text"
  },
  { // array 10
    managerID: "1256320322135674880",
    name: "Brian James",
    teamName: "Kodachromes",
    location: "FL",
    bio: "In the fast-paced world of fantasy football, every moment matters. The Kansas City Kodachromes are a team built on precision timing, artistic vision, and a knack for making even the most chaotic situations look effortlessly composed. No mama, you will not take our Kodachrome away! K.C. is in focus, in frame, and always ready for the perfect shot.",
    photo: "/managers/kodachromes.png",
    fantasyStart: 2018,
    favoriteTeam: "kc",
    mode: "Rebuild",
    rival: { name: "Clifton McVay", link: 4, image: "/managers/hipsterJacks.png" },
    yearsOfService: null,
    persona: "The Wolf",
    philosophy: "In focus, in frame, never fading.",
    championship: { league: null, years: null },
    preferredContact: "Text"
  },
  { // array 11
    managerID: "857309838424809472",
    name: "Brian Marx",
    teamName: "Tallahassee Tribe",
    location: "FL",
    bio: "One people. One team. One destiny. In the heart of Florida’s capital city, rides the Tallahassee Tribe—a fantasy football team as fierce as the Seminoles wandering through the desert for forty years without so much as a bye week. The Tribe don’t just play the game, they honor it with generational perseverance, courage, and chutzpah. With a single championship in its past, Tallahassee is ready to celebrate its next victory with both a war chant and a L’chaim!",
    photo: "/managers/tribe.png",
    fantasyStart: 2023,
    favoriteTeam: "tb",
    mode: "Rebuild",
    rival: { name: "Romano DeSimone", link: 8, image: "/managers/vincitori.png" },
    yearsOfService: null,
    persona: "The Littlefinger",
    philosophy: "One people. One team. One Destiny.",
    championship: { league: "DTSP", years: "2022" },
    preferredContact: "Text"
  },
   { // array 12
    managerID: "1258962574360182785",
    name: "Adam Lopiano",
    teamName: "Saskatchewan Mounties",
    location: "CT",
    bio: "The Saskatchewan backstory is a collection of half-whispered tales from the frozen north, each one stranger than the last. Whether true or not? That’s part of the fun! The Mounties hail from that peculiar intersection where Vermont maple syrup meets Canadian politeness, where vintage isn't a style choice its a uniform! It should be known, we are the Mounties and the Mounties always get their man… and by “man,” we mean your starting quarterback!",
    photo: "/managers/mounties.png",
    fantasyStart: 2004,
    favoriteTeam: "nyg",
    mode: "Rebuild",
    rival: { name: "Jason Gray", link: 7, image: "/managers/jayhawks.png" },
    yearsOfService: null,
    persona: "The Flacco",
    philosophy: "The Mounties always get their man!",
    championship: { league: "Irving", years: "2006" },
    preferredContact: "Text"
  },
  { // array 13
    managerID: "1260985941263126528",
    name: "Brad Thornton",
    teamName: "Clearwater HenryPussycats",
    location: "FL",
    bio: "The Clearwater Henry Pussycats prowl the league waiting for the moment to strike. The cats are sharp-eyed and never fooled by the noise of the crowd. With postal efficiency and data analytics driving the way, Clearwater deliver victories like a perfectly addressed letter arriving at the opponents door on time, certified and signed, yours truly Henry Pussycat, purrrr!",
    photo: "/managers/henry.png",
    fantasyStart: 2010,
    favoriteTeam: "mia",
    mode: "Rebuild",
    rival: { name: "James Barmore", link: 9, image: "/managers/homers.png" },
    yearsOfService: null,
    persona: "The Kornacki",
    philosophy: "We strike on time, certified and signed.",
    championship: { league: "Irving", years: "2010, 2014" },
    preferredContact: "Text"
  },
];
